name: Monthly Email Notification

on:
  schedule:
    # Runs at 00:00 from the 28th to the 31st of every month
    - cron: '0 0 28-31 * *'

jobs:
  send-monthly-email:
    runs-on: ubuntu-latest
    steps:
      - name: Call Email Notification Endpoint
        run: curl -sS https://cibus-reminder-production.up.railway.app/
